export enum IRoute {
  HOME = "/",
  DASHBOARD = "/dashboard",
  DEVICES = "/thiet-bi",
  SERVICES = "/dich-vu",
  REPORT = "/bao-cao",
  SETTINGS = "/cai-dat",
  LOGIN = "/dang-nhap",
  CHANGE_PASSWORD = "/doi-mat-khau",
  INFO = "/thong-tin",
  ADD_DEVICE = "/thiet-bi/them-thiet-bi",
  DEVICE_DETAIL = "/thiet-bi/chi-tiet-thiet-bi",
  ADD_SERVICE = "/dich-vu/them-dich-vu",
  SERVICE_DETAIL = "/dich-vu/chi-tiet-dich-vu",
  NUMBER_PROVIDATION = "/cap-so",
  NUMBER_PROVIDATION_CREATE = "/cap-so/cap-so-moi",
  NUMBER_PROVIDATION_DETAIL = "/cap-so/chi-tiet",
  SETTINGS_ADD_ROLE = "/cai-dat/them-vai-tro",
  SETTINGS_ROLE = "/cai-dat/quan-ly-vai-tro",
  SETTINGS_ACCOUNT = "/cai-dat/tai-khoan",
  SETTINGS_ADD_ACCOUNT = "/cai-dat/them=tai-khoan",
  SETTINGS_USER = "/cai-dat/nguoi-dung",
}
