export enum IRoute {
  HOME = "/",
  DASHBOARD = "/dashboard",
  DEVICES = "/thiet-bi",
  SERVICES = "/dich-vu",
  NUMBER_PROVIDATION = "/cap-so",
  REPORT = "/bao-cao",
  SETTINGS = "/cai-dat",
  LOGIN = "/dang-nhap",
  CHANGE_PASSWORD = "/doi-mat-khau",
  INFO = "/thong-tin",
  ADD_DEVICE = "/thiet-bi/them-thiet-bi",
  DEVICE_DETAIL = "/thiet-bi/chi-tiet-thiet-bi",
  ADD_SERVICE = "/dich-vu/them-dich-vu",
  SERVICE_DETAIL = "/dich-vu/chi-tiet-dich-vu",
}
